//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int Id { get; set; }
        public string Office1 { get; set; }
        public decimal Mileage { get; set; }
        public decimal MileageCompleted { get; set; }
        public int ListOrder { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
