//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOpenAuthData
    {
        public UsersOpenAuthData()
        {
            this.UsersOpenAuthAccounts = new HashSet<UsersOpenAuthAccount>();
        }
    
        public string ApplicationName { get; set; }
        public string MembershipUserName { get; set; }
        public bool HasLocalPassword { get; set; }
    
        public virtual ICollection<UsersOpenAuthAccount> UsersOpenAuthAccounts { get; set; }
    }
}
