//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwActivitiesByUser
    {
        public Nullable<long> RowNumber { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> TotalMileage { get; set; }
        public System.Guid UserId { get; set; }
    }
}
