//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwActivity
    {
        public System.Guid UserId { get; set; }
        public decimal Mileage { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string ActivityType { get; set; }
    }
}
